services:
  sep_proxy:
    container_name: "sep_proxy"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"

  nginx:
    container_name: "nginx"
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - sep_proxy